--SELECT * FROM CUSTOMER;
--SELECT FIRSTNAME, LASTNAME FROM CUSTOMER;
--SELECT * FROM CUSTOMER WHERE FIRSTNAME = 'Dan';
--SELECT * FROM CUSTOMER WHERE STATE = 'CA' AND FIRSTNAME LIKE 'D%';
--SELECT ARTISTID FROM ARTIST WHERE NAME = 'AC/DC';
--SELECT ALBUMID FROM ALBUM WHERE ARTISTID = 1;
--SELECT * FROM TRACK WHERE ALBUMID = 1 OR ALBUMID = 4;

SELECT * FROM ARTIST OUTER INNER JOIN ALBUM ON ARTIST.ARTISTID = ALBUM.ARTISTID;

CREATE VIEW ACDC_SONGS AS SELECT * FROM TRACK WHERE ALBUMID IN (SELECT ALBUMID FROM ALBUM WHERE ARTISTID = (SELECT ARTISTID FROM ARTIST WHERE NAME = 'AC/DC'));

SELECT * FROM ACDC_SONGS;

CREATE VIEW ACDC_PLAYLISTS AS SELECT * FROM PLAYLIST WHERE PLAYLISTID IN 
(SELECT PLAYLISTID FROM PLAYLISTTRACK WHERE TRACKID IN (SELECT TRACKID FROM ACDC_SONGS));

SELECT * FROM ACDC_PLAYLISTS;

SELECT * FROM TRACK WHERE TRACKID NOT IN (SELECT TRACKID FROM ACDC_SONGS) AND TRACKID IN 
(SELECT TRACKID FROM PLAYLISTTRACK WHERE PLAYLISTID IN (SELECT PLAYLISTID FROM ACDC_PLAYLISTS));

SELECT * FROM TRACK WHERE TRACKID IN
(SELECT TRACKID FROM PLAYLISTTRACK WHERE PLAYLISTID IN
  (SELECT PLAYLISTID FROM PLAYLISTTRACK WHERE TRACKID IN
    (SELECT TRACKID FROM TRACK WHERE ALBUMID IN 
      (SELECT ALBUMID FROM ALBUM WHERE ARTISTID = 
        (SELECT ARTISTID FROM ARTIST WHERE NAME = 'AC/DC')
    ))) AND TRACKID NOT IN 
      (SELECT TRACKID FROM TRACK WHERE ALBUMID IN 
        (SELECT ALBUMID FROM ALBUM WHERE ARTISTID = 
          (SELECT ARTISTID FROM ARTIST WHERE NAME = 'AC/DC'))));