CREATE OR REPLACE PROCEDURE REMOVE_EMP(EMP_ID NUMBER, ASSOCIATES OUT SYS_REFCURSOR)
  AS
  ASSOC_ID INT;
  BEGIN
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    OPEN ASSOCIATES FOR SELECT EMPLOYEEID FROM EMPLOYEE WHERE REPORTSTO = EMP_ID;
    LOOP
      FETCH ASSOCIATES INTO ASSOC_ID;
    EXIT WHEN ASSOCIATES%NOTFOUND;
    
    UPDATE EMPLOYEE SET REPORTSTO = 1 WHERE EMPLOYEEID = ASSOC_ID;
    
    END LOOP;
    
    DELETE FROM EMPLOYEE WHERE EMPLOYEEID = EMP_ID;
  COMMIT;
  END;